# Generated by Django 3.0.7 on 2021-05-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200603_0650'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTelegramNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo', models.TimeField(blank=True, null=True)),
                ('tu', models.TimeField(blank=True, null=True)),
                ('we', models.TimeField(blank=True, null=True)),
                ('th', models.TimeField(blank=True, null=True)),
                ('fr', models.TimeField(blank=True, null=True)),
                ('sa', models.TimeField(blank=True, null=True)),
                ('su', models.TimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to='core.Item')),
            ],
        ),
    ]
