# Generated by Django 3.0.6 on 2020-06-02 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200602_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('owner', 'name')},
        ),
    ]
