# Generated by Django 3.0.6 on 2020-06-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200602_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Folder'),
        ),
    ]
